---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: spring-k8s-jpa
data:
  # You may have to edit these properties depending on the database name.
  SPRING_DATASOURCE_URL: jdbc:postgresql://pgdb-postgresql/
  SPRING_DATASOURCE_USERNAME: postgres
