---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: spring-k8s-jpa
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
        - name: app
          image: alexandreroman/spring-k8s-jpa-demo:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          # Uncomment to inject datasource credentials
          # (you may have to edit the secret name from the database deployment).
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgdb-postgresql
                  key: postgresql-password
          envFrom:
            - configMapRef:
                name: app
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 1
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            failureThreshold: 6
