---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: spring-k8s-jpa
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    role: app
