---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-k8s-jpa
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
configMapGenerator:
  - name: app
    literals:
      - spring.datasource.url=jdbc:postgresql://pgdb-postgresql/
      - spring.datasource.username=postgres
